# Generated by Django 5.0.7 on 2026-04-08 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.CharField(blank=True, max_length=255)),
                ('approach', models.CharField(blank=True, max_length=255)),
                ('experience', models.TextField(blank=True)),
                ('focus_areas', models.TextField(blank=True)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('location_lines', models.JSONField(blank=True, default=list)),
                ('image_url', models.TextField(blank=True)),
                ('secret_passphrase_hash', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
