# Generated by Codex on 2026-05-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapists", "0002_seed_kelvin_kagiri"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientStory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(blank=True, max_length=160)),
                ("image_url", models.TextField(blank=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Therapy"),
                            ("family", "Family Therapy"),
                            ("corporate", "Corporate Wellness"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("story_text", models.TextField()),
                ("edited_story_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending Review"), ("published", "Published")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_stories",
                        to="therapists.therapistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
