# Generated by Django 5.0.7 on 2026-04-08 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manage_token', models.CharField(db_index=True, max_length=48, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=64)),
                ('therapist_name_snapshot', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family'), ('corporate', 'Corporate')], max_length=20)),
                ('participant_count', models.PositiveIntegerField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('location_summary', models.TextField()),
                ('calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('meet_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='therapists.therapistprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('created', 'Created'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('confirmation', 'Confirmation'), ('reschedule', 'Reschedule'), ('cancellation', 'Cancellation')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('html', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
