# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_booking_booking_fee_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpayment",
            name="payer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="bookingpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("stk_push_sent", "STK Push Sent"),
                    ("processing", "Processing"),
                    ("manual_review", "Manual Review"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("timed_out", "Timed Out"),
                    ("insufficient_funds", "Insufficient Funds"),
                ],
                default="initiated",
                max_length=32,
            ),
        ),
    ]
