# Generated by Django 5.0.7 on 2026-04-28 15:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_refresh_virtual_session_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_fee_currency',
            field=models.CharField(default='KES', max_length=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_failed', 'Payment Failed'), ('upcoming', 'Upcoming'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookinghistoryevent',
            name='type',
            field=models.CharField(choices=[('created', 'Created'), ('payment_initiated', 'Payment Initiated'), ('payment_failed', 'Payment Failed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('stk_push_sent', 'STK Push Sent'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out'), ('insufficient_funds', 'Insufficient Funds')], default='initiated', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('phone_number', models.CharField(max_length=32)),
                ('account_reference', models.CharField(blank=True, max_length=64)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('checkout_request_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('result_code', models.CharField(blank=True, max_length=32)),
                ('result_description', models.TextField(blank=True)),
                ('transaction_id', models.CharField(blank=True, max_length=128)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_check_at', models.DateTimeField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('query_payload', models.JSONField(blank=True, default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
