# Generated by Django 5.0.7 on 2026-04-08 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('bookings', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel'), ('completion', 'Completion'), ('blog', 'Blog')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blog.blogpost')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='therapists.therapistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
