# Generated by Codex on 2026-05-28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("therapists", "0002_seed_kelvin_kagiri"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp_mobile", models.CharField(max_length=40)),
                ("subject", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField()),
                ("status", models.CharField(choices=[("open", "Open"), ("replied", "Replied")], default="open", max_length=20)),
                ("reply_message", models.TextField(blank=True)),
                ("replied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "replied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replied_contact_inquiries",
                        to="therapists.therapistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("reschedule", "Reschedule"),
                    ("cancel", "Cancel"),
                    ("completion", "Completion"),
                    ("blog", "Blog"),
                    ("inquiry", "Inquiry"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="inquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="notifications.contactinquiry",
            ),
        ),
    ]
