# Generated by Django 5.0.7 on 2026-04-08 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('publish_date', models.DateField()),
                ('author_name', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('featured_image_url', models.TextField(blank=True)),
                ('content_html', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='therapists.therapistprofile')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
